version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - MONGO_URI=mongodb://db:27017/mydatabase
  db:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data: