import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import Chat from '@/components/Chat'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Study Overseas - Axelis Overseas',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <Navbar/>          
          <Chat/>
        {children}
        <Footer/>
        </div>        
      </body>
    </html>
  )
}
